window.Game=(function(){const C=window.CONFIG;function spawnPlayer(id){if(id===1)return{id:1,x:40,y:40,w:24,h:24,vx:0,vy:0,facing:'down',health:C.PLAYER_MAX_HEALTH,wins:0,lastShotAt:0,weapon:'laser',invulnUntil:0};return{id:2,x:C.CANVAS_WIDTH-64,y:C.CANVAS_HEIGHT-64,w:24,h:24,vx:0,vy:0,facing:'down',health:C.PLAYER_MAX_HEALTH,wins:0,lastShotAt:0,weapon:'laser',invulnUntil:0};}
function create(canvas){return{canvas,ctx:canvas.getContext('2d'),level:window.LEVEL_01,players:[spawnPlayer(1),spawnPlayer(2)],projectiles:[],effects:[],pickups:window.Pickups.createSystem(),debug:{grid:C.DEBUG_GRID_DEFAULT,collision:C.DEBUG_COLLISION_DEFAULT},paused:false,now:0,roundResetAt:0};}
function movePlayer(g,p,dx,dy,dt){const sp=C.PLAYER_SPEED;let nx=p.x+dx*sp*dt,ny=p.y+dy*sp*dt;const bx=(p.w-C.PLAYER_COLLISION_BOX.w)/2,by=(p.h-C.PLAYER_COLLISION_BOX.h)/2;if(!window.Collision.isBlockedPixelRect(g.level,nx+bx,p.y+by,C.PLAYER_COLLISION_BOX.w,C.PLAYER_COLLISION_BOX.h))p.x=nx;if(!window.Collision.isBlockedPixelRect(g.level,p.x+bx,ny+by,C.PLAYER_COLLISION_BOX.w,C.PLAYER_COLLISION_BOX.h))p.y=ny;}
function update(game,dt,now){game.now=now;if(window.Input.isDown('KeyP')&&!game._p){game.paused=!game.paused;}game._p=window.Input.isDown('KeyP');if(window.Input.isDown('KeyG')&&!game._g){game.debug.grid=!game.debug.grid;}game._g=window.Input.isDown('KeyG');if(window.Input.isDown('KeyC')&&!game._c){game.debug.collision=!game.debug.collision;}game._c=window.Input.isDown('KeyC');if(game.paused)return;if(game.roundResetAt&&now>=game.roundResetAt){const w1=game.players[0].wins,w2=game.players[1].wins;game.players=[spawnPlayer(1),spawnPlayer(2)];game.players[0].wins=w1;game.players[1].wins=w2;game.projectiles=[];game.roundResetAt=0;}
const p1=game.players[0],p2=game.players[1];let d1x=(window.Input.isDown('KeyD')?1:0)-(window.Input.isDown('KeyA')?1:0),d1y=(window.Input.isDown('KeyS')?1:0)-(window.Input.isDown('KeyW')?1:0),d2x=(window.Input.isDown('ArrowRight')?1:0)-(window.Input.isDown('ArrowLeft')?1:0),d2y=(window.Input.isDown('ArrowDown')?1:0)-(window.Input.isDown('ArrowUp')?1:0);
for(const [p,dx,dy] of [[p1,d1x,d1y],[p2,d2x,d2y]]){if(dx||dy){const m=Math.hypot(dx,dy);p.vx=dx/m;p.vy=dy/m; if(Math.abs(dx)>Math.abs(dy))p.facing=dx<0?'left':'right';else p.facing=dy<0?'up':'down'; movePlayer(game,p,p.vx,p.vy,dt);}else{p.vx=0;p.vy=0;}}
if(window.Input.isDown('Space'))window.Weapons.tryFire(game,p1,now);if(window.Input.isDown('Numpad0'))window.Weapons.tryFire(game,p2,now);
window.Weapons.updateProjectiles(game,dt);game.effects=game.effects.filter(e=>e.until>now);window.Pickups.update(game,dt);
if(!game.roundResetAt&&(p1.health<=0||p2.health<=0)){if(p1.health<=0)p2.wins++;if(p2.health<=0)p1.wins++;game.roundResetAt=now+C.ROUND_RESET_DELAY_MS;}}
return{create,update};})();
